"""create_transactions_and_transaction_events

Revision ID: 2a74387b54f3
Revises: 57d2f1edaaba
Create Date: 2026-08-18 21:34:52.809164

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2a74387b54f3'
down_revision: Union[str, Sequence[str], None] = '57d2f1edaaba'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
